### ISSUE TITLE
Implement with hooks

### ISSUE THREAD

**Issue by frostming** [gazpachoking/pdm-buildlocked#1]
While the current implementation works for build command, but not for `publish` command, which also build distributions under the hood.

Ideally, this should be solved by using `pre_buid` and `post_build` hooks.

**Comment by gazpachoking** [comment]
Hmm, yes, that would be nice. Right now I was doing a publish with --no-build after doing the build. Couple questions though:
- I don't see any way that publish command passes options to the build action (or more importantly the hooks in the build action.) I'm assuming we would override the publish command with an option, like `pdm publish --locked`, but then how would that option get to the build hooks?
- I'm a bit worried about taking the restoration of the pyproject.toml out of the try..finally block. If something went wrong during build, we wouldn't want the user's pyproject.toml to be permanently changed if the post_build hook never ran somehow.

**Comment by gazpachoking** [comment]
Oh, perhaps it would be better to specify that the build should be locked in the pyproject.toml. That way we don't need to override either the `build` or `publish` command to add a cli flag. I still worry a bit about the post_ hook not running for some reason and leaving the user's pyproject in a modified state though.

**Comment by gazpachoking** [comment]
@lecardozo @lofidevops Would moving the locked option to the pyproject fit with your workflows?

`[tool.pdm.buildlocked]` or something?

**Comment by frostming** [comment]
Oh, if you want to make it opt-in, then overriding the command is fine.

**Comment by gazpachoking** [comment]
> Oh, if you want to make it opt-in, then overriding the command is fine.

Yeah, I think it needs to be opt in, at least at the project level. But I think having it in pyproject is actually better, because you probably want it consistent for all builds for a particular project. I'll look in to the hooks, it would certainly be nice if it worked with publish command as well.

**Comment by gazpachoking** [comment]
Decided this was probably a good idea. #2
